[project]
name = "WEGPrecos"
version = "0.1.0"
description = "Calculo de preços a partir do código WEG"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "playwright>=1.55.0",
    "xlwings>=0.33.16",
]
