[project]
name = "wegprecos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "playwright>=1.56.0",
    "xlwings>=0.33.17",
]
